// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type Character struct {
	ID     int64
	Name   string
	Race   string
	Class  string
	Damage int64
	Level  int64
}

type Inventory struct {
	ID          int64
	CharacterID int64
	Name        string
	Damage      int64
	Price       int64
	Class       string
	Quantity    int64
}

type Slot struct {
	CharacterID int64
	Slot        string
	Name        string
	Damage      int64
	Price       int64
	Class       string
}
